# Generated by Django 2.2.1 on 2019-07-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GJJ', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('SYDK', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
            ],
        ),
    ]
