"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

import sys
sys.path.insert(0, os.path.join(BASE_DIR, 'apps'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'r=r)2-h9*_+6qwtc0=(1a3fw7=d5jig54p&jav^8s8p*3vm7)a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # for blog
    'blog',
    # for allauth 用户注册与登录
    'django.contrib.sites',
    'allauth',
    'allauth.account',    
    'allauth.socialaccount',
    'allauth.socialaccount.providers.baidu',   #百度登陆所需
    'allauth.socialaccount.providers.weibo',
    # for crispy 表单美化
    'crispy_forms',
    # for myauth 添加用户签名字段
    'myauth',
    # for image 用于用户头像管理
    'imagekit',
    # for ckeditor 富文本编辑器，用于管理文章和评论
    'ckeditor',
    'ckeditor_uploader',

]

SITE_ID = 1
#作用是登录时可以用用户名也可以用邮箱
ACCOUNT_AUTHENTICATION_METHOD = 'username_email'
#作用是注册时，邮箱是必备的。
ACCOUNT_EMAIL_REQUIRED = True
#禁用注册邮箱验证
ACCOUNT_EMAIL_VERIFICATION='none'
#登出时直接退出，不用确认
ACCOUNT_LOGOUT_ON_GET=True

CRISPY_TEMPLATE_PACK = 'bootstrap3'

# 重载auth_model
AUTH_USER_MODEL = 'myauth.Myuser'

# 配置发送找回密码的邮箱
EMAIL_HOST = 'smtp.163.com'            #配置smtp地址
EMAIL_HOST_USER = 'mmiixxuu@163.com'    #配置邮箱地址 
EMAIL_HOST_PASSWORD = 'mi901006Xur'         #配置授权码，注意是授权码，不是邮箱密码
EMAIL_PORT = 465                       #端口号
EMAIL_USE_SSL = True                   #指定SSL发送
EMAIL_FROM = "MyBlog"                  #可以指定邮件发件人
DEFAULT_FROM_EMAIL = 'Example<example@163.com>' 

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 指定 CKEditor 文件上传保存路径
CKEDITOR_UPLOAD_PATH = 'ckeditor_upload'