# Generated by Django 2.2.3 on 2019-07-29 07:55

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_myuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(default='avatar/x01.png', upload_to='avatar', verbose_name='头像'),
        ),
    ]
