# Generated by Django 2.2.3 on 2019-08-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title',
        ),
        migrations.AddField(
            model_name='blog',
            name='monthlyInterest',
            field=models.FloatField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='monthlyPayment',
            field=models.FloatField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='monthlyPrincipal',
            field=models.FloatField(default=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='terms',
            field=models.IntegerField(default=True),
        ),
    ]
